logging:
  level:
    org.springframework: debug

server:
  servlet:
    context-path: /resServer
  port: 7081

spring:
  mvc:
    view:
      prefix: /page
      suffix: .html

  # DataSource
  datasource:
    password: ''
    url: jdbc:mysql://localhost/oauth2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  oauth2:
    client:
      client-id: resServerDemo
      client-secret: resServerDemosecret
      registered-redirect-uri: http://localhost:7081/resServer/oauth2Redirect
