custom:
  security:
    test-uri-pattern: /test/**
    oauth2-client-id: resServer
    oauth2-client-secret: resServerSecret
    oauth2-redirect-url: http://localhost:7081/resServer/oauth2/redirect
    oauth2-scope: all