logging:
  level:
    org.springframework: debug

server:
  servlet:
    context-path: /authServer
  port: 7080

spring:
  mvc:
    view:
      prefix: /page
      suffix: .html

  # DataSource
  datasource:
    password: ''
    url: jdbc:mysql://localhost/oauth2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 5000ms
