server:
  servlet:
    context-path: /authServer
  port: 7081

spring:
  mvc:
    view:
      prefix: /page
      suffix: .html

  # DataSource
  datasource:
    password: ''
    url: jdbc:mysql://localhost/oauth2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  oauth2:
    client:
      client-id: demo
      client-secret: demosecret
      registered-redirect-uri: http://www.baidu.com