custom:
  security:
    redis-session-alive-minutes: 30
    oauth2-approval-request: /oauth2/approval
    oauth2-grant-type: custom
    oauth2-authcode-alive-seconds: 3600
    test-uri-pattern: /test/**
    login-page-uri: /login